### ISSUE TITLE
Einheitlicher Name

### ISSUE THREAD

**Issue by KaiFra** [freeDSP/freeDSP-ALLinONE#15]
In Absprache mit Tom hatten wir uns auf "freeDSP AiO" als Name für unser Projekt geeinigt.
Deswegen sollten wir hier und im Doc alles bis zur Abgabe vereinheitlicht haben.

**Comment by michael-schindler** [comment]
> Wir haben uns jetzt auf freeDSP ALLinONE geeinigt

Na dann würde ich das Issue an dieser Stelle mal schließen, zumal wir ja jetzt ohnehin live sind.

**Comment by KaiFra** [comment]
Naja, auf dem PCB steht es noch nicht so und im GS sind die Bilder damit auch veraltet
