### ISSUE TITLE
Wiki auf neusten Stand bringen

### ISSUE THREAD

**Issue by KaiFra** [freeDSP/freeDSP-ALLinONE#18]
Hat jetzt nicht unbedingt Priorität, aber bei freien Kapazitäten könnte man das Wiki noch aufhübschen, komplett auf Englisch halten und es auf denselben Stand wie das Doc bringen
Also Bilder einfügen und die Leiste an der Seite anpassen, sodass es eine Unterleiste gibt, wenn man auf Messungen geht

**Comment by michael-schindler** [comment]
> Messungen einpflegen

Das ist ja bereits im #20 dabei. #18 ist für das Allgemeine.

**Comment by KaiFra** [comment]
done
